require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClinicsController do

  # This should return the minimal set of attributes required to create a valid
  # Clinic. As you add validations to Clinic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClinicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all clinics as @clinics" do
      clinic = Clinic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clinics).should eq([clinic])
    end
  end

  describe "GET show" do
    it "assigns the requested clinic as @clinic" do
      clinic = Clinic.create! valid_attributes
      get :show, {:id => clinic.to_param}, valid_session
      assigns(:clinic).should eq(clinic)
    end
  end

  describe "GET new" do
    it "assigns a new clinic as @clinic" do
      get :new, {}, valid_session
      assigns(:clinic).should be_a_new(Clinic)
    end
  end

  describe "GET edit" do
    it "assigns the requested clinic as @clinic" do
      clinic = Clinic.create! valid_attributes
      get :edit, {:id => clinic.to_param}, valid_session
      assigns(:clinic).should eq(clinic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clinic" do
        expect {
          post :create, {:clinic => valid_attributes}, valid_session
        }.to change(Clinic, :count).by(1)
      end

      it "assigns a newly created clinic as @clinic" do
        post :create, {:clinic => valid_attributes}, valid_session
        assigns(:clinic).should be_a(Clinic)
        assigns(:clinic).should be_persisted
      end

      it "redirects to the created clinic" do
        post :create, {:clinic => valid_attributes}, valid_session
        response.should redirect_to(Clinic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clinic as @clinic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clinic.any_instance.stub(:save).and_return(false)
        post :create, {:clinic => { "name" => "invalid value" }}, valid_session
        assigns(:clinic).should be_a_new(Clinic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clinic.any_instance.stub(:save).and_return(false)
        post :create, {:clinic => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clinic" do
        clinic = Clinic.create! valid_attributes
        # Assuming there are no other clinics in the database, this
        # specifies that the Clinic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Clinic.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => clinic.to_param, :clinic => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested clinic as @clinic" do
        clinic = Clinic.create! valid_attributes
        put :update, {:id => clinic.to_param, :clinic => valid_attributes}, valid_session
        assigns(:clinic).should eq(clinic)
      end

      it "redirects to the clinic" do
        clinic = Clinic.create! valid_attributes
        put :update, {:id => clinic.to_param, :clinic => valid_attributes}, valid_session
        response.should redirect_to(clinic)
      end
    end

    describe "with invalid params" do
      it "assigns the clinic as @clinic" do
        clinic = Clinic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clinic.any_instance.stub(:save).and_return(false)
        put :update, {:id => clinic.to_param, :clinic => { "name" => "invalid value" }}, valid_session
        assigns(:clinic).should eq(clinic)
      end

      it "re-renders the 'edit' template" do
        clinic = Clinic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clinic.any_instance.stub(:save).and_return(false)
        put :update, {:id => clinic.to_param, :clinic => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clinic" do
      clinic = Clinic.create! valid_attributes
      expect {
        delete :destroy, {:id => clinic.to_param}, valid_session
      }.to change(Clinic, :count).by(-1)
    end

    it "redirects to the clinics list" do
      clinic = Clinic.create! valid_attributes
      delete :destroy, {:id => clinic.to_param}, valid_session
      response.should redirect_to(clinics_url)
    end
  end

end
